---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-cvmfs-cms
provisioner: cvmfs.csi.cern.ch
parameters:
  repository: cms.cern.ch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-cvmfs-cms-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-cvmfs-cms
---
kind: Service
apiVersion: v1
metadata:
  name: newdqmgui
  namespace: dqm
spec:
  selector:
    app: newdqmgui
  ports:
    - port: 8889
      targetPort: 8889
      name: newdqmgui
    - port: 18889
      targetPort: 18889
      name: newdqmgui-mon
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: newdqmgui
  labels:
    app: newdqmgui
  namespace: dqm
data:
  setup-certs-and-run.sh: |
    #!/bin/bash

    sudo cp /host/etc/grid-security/* /etc/grid-security
    echo 'INFO Files in /etc/grid-security'
    ls -lahZ /etc/grid-security
    cd /home/cmsusr/dqmgui/dqmgui && ./run.sh
---    
kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: newdqmgui
  name: newdqmgui
  namespace: dqm
spec:
  selector:
    matchLabels:
      app: newdqmgui
  replicas: 1 #PROD# 1
  template:
    metadata:
      labels:
        app: newdqmgui
        env: k8s #k8s#
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: "18889"
    spec:
      # use hostNetwork to allow communication between newdqmgui/reqmon/workqueue and couch
#       hostNetwork: true
#       dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 2000
      containers:
      - image: registry.cern.ch/cmsweb/newdqmgui #imagetag
        name: newdqmgui
        command: ["./run.sh"]
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "3Gi"
            cpu: "1000m"
        ports:
        - containerPort: 8889
          protocol: TCP
          name: newdqmgui
        - containerPort: 18889
          protocol: TCP
          name: newdqmgui-mon
        command:
        - /bin/bash
        - /opt/setup-certs-and-run/setup-certs-and-run.sh
        volumeMounts:
        - mountPath: /dev/fuse
          name: fuse
        - name: proxy-secrets
          mountPath: /etc/proxy
          readOnly: true
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: robot-secrets
          mountPath: /etc/robots
          readOnly: true
        - name: hmac-secrets
          mountPath: /etc/hmac
          readOnly: true
        - mountPath: /host/etc/grid-security
          name: etc-grid-security
          readOnly: true
        - name: setup-certs-and-run
          mountPath: /opt/setup-certs-and-run
        - name: token-secrets
          mountPath: /etc/token
          readOnly: true
        - name: eos
          mountPath: /eos
          mountPropagation: HostToContainer
        - name: eos-krb
          mountPath: /tmp/krb
        - mountPath: /cvmfs/cms.cern.ch
          name: cms-pvc                    
#PROD#  - name: logs
#PROD#    mountPath: /home/cmsusr/dqmgui/dqmgui
        securityContext:
          privileged: true
          capabilities:
            add:
              - SYS_ADMIN
      volumes:
      - name: fuse
        hostPath:
          path: /dev/fuse
      - name: proxy-secrets
        secret:
          secretName: proxy-secrets
      - name: secrets
        secret:
          secretName: newdqmgui-secrets
      - name: robot-secrets
        secret:
          secretName: robot-secrets
      - name: hmac-secrets
        secret:
          secretName: hmac-secrets
      - name: etc-grid-security
        hostPath:
            path: /etc/grid-security
      - name: setup-certs-and-run
        configMap:
          name: newdqmgui
      - name: token-secrets
        secret:
          secretName: token-secrets
      - name: eos
        hostPath:
          path: /var/eos
      - name: eos-krb
        secret:
          secretName: eos-krb          
      - name: cms-pvc
        persistentVolumeClaim:
          claimName: csi-cvmfs-cms-pvc
          readOnly: true
#PROD#- name: logs
#PROD#  persistentVolumeClaim:
#PROD#      claimName: logs-cephfs-claim-dqm

