#!/bin/bash -ex

# Script to build an RPM package for the new DQMGUI
# Required packages to run this script: python3, python3-pip, curl, rpmdevtools
# Run this from the same directory where this script is.

BUILD_ARCH=x86_64
TOPDIR=$PWD

# Where the RPM will install files to
INSTALLATION_DIR=/dqmgui

# Where PB and ROOT files will be expected. Will be created if it does not exist
DQMGUI_DATA_DIR=/data/dqmgui

# Installation machine's CMSSW base directory
CMSSW_BASE_DIR=/dqmdata/dqm_cmssw

# TODO: Use the above paths to automatically modify the paths in the service files

#Check is release version is provided
if [[ -z "$1" ]]; then
    echo "Please provide DQM GUI version; tags can be found here: https://github.com/cms-DQM/dqmgui/tags"
    exit
fi

DQM_GUI_RELEASE_VERSION=$1

# Cleanup before building
rm -rf ./*.tar.gz*
rm -rf ./*.rpm
rm -rf ./dqmgui
rm -rf ./dqmgui-${DQM_GUI_RELEASE_VERSION}

# Check python version
# We should probably check for a more specific version at some point.
if [[ "$(python3 -V)" =~ "Python 3" ]]; then
    echo "Python 3 is installed"
else
    echo "Error: Python 3 is not installed"
    exit 1
fi
# Download DQMGUI's source in the background

curl -L "https://github.com/cms-DQM/dqmgui/archive/refs/tags/${DQM_GUI_RELEASE_VERSION}.tar.gz" -o "${DQM_GUI_RELEASE_VERSION}.tar.gz" &

# Use pip to download dependecies and bundle them in the RPM
# This should probably be a requirements.txt file
python3 -m pip install contextvars==2.4 async-lru==1.0.2 aiosqlite==0.13.0 aiohttp==3.6.2 setuptools -t .python_packages
python3 -m pip install Cython --install-option="--no-cython-compile" -t .python_packages

# Wait in case curl is not done
wait

# Move python packages to DQM GUI dir
tar -xzvf "${DQM_GUI_RELEASE_VERSION}.tar.gz"
mv .python_packages "dqmgui-${DQM_GUI_RELEASE_VERSION}/python/"
tar -czvf "${DQM_GUI_RELEASE_VERSION}.tar.gz" "dqmgui-${DQM_GUI_RELEASE_VERSION}"
mkdir dqmgui
mv "${DQM_GUI_RELEASE_VERSION}.tar.gz" dqmgui

# Cleanup
rm -rf "dqmgui-${DQM_GUI_RELEASE_VERSION}"

# Create the RPM spec file
cat >dqmgui-lib.spec <<EOF
Name: DQM_GUI
Version: ${DQM_GUI_RELEASE_VERSION}
Release: 1
Summary: DQM GUI software
License: gpl
Group: CERN CMS DQM-DC
Packager: Ernesta Petraityte
Source0: "${DQM_GUI_RELEASE_VERSION}.tar.gz"
%define _tmppath %{getenv:PWD}/dqmgui_rpm
BuildRoot:  %{_tmppath}
BuildArch: x86_64
AutoReqProv: no

%description
DQM GUI and required python dependecies

%prep
echo  %{_tmppath}

%build

%install
rm -rf \$RPM_BUILD_ROOT
mkdir -p \$RPM_BUILD_ROOT
tar -C %{getenv:PWD} -c dqmgui | tar -xC \$RPM_BUILD_ROOT

%post
#### extracting tar, moving older release to old_release folder
#### This is meant to be run on P5 machines.

set -x

HOST=\$(hostname)

# Figure out the type of installation we're doing
# and configure the CMSSW path in the P5 NFS.
# This should probably not be hardcoded.
DQMGUI_MODE_PATH=""
if [ "\$HOST"="dqmsrv-c2a06-08-01" ];
then
    DQMGUI_MODE_PATH="$CMSSW_BASE_DIR/current_playback"
elif [ "\$HOST" = "dqmsrv-c2a06-07-01" ];
then
    DQMGUI_MODE_PATH="$CMSSW_BASE_DIR/current_production"
else
    echo "This RPM is only meant to be installed in DQMGUI machines!"
    exit 1
fi
cd $INSTALLATION_DIR
tar -xzvf ${DQM_GUI_RELEASE_VERSION}.tar.gz

# Overwrite existing installation files
mv ./dqmgui-${DQM_GUI_RELEASE_VERSION}/* .
rm -rf ./dqmgui-${DQM_GUI_RELEASE_VERSION}

# if [[ -d "$INSTALLATION_DIR/old_releases" ]]
# then
#     echo "cannot create directory ‘old_releases’: File exists"
# else
#     exec mkdir old_releases
# fi

# mv ./1.0.15.tar.gz ./old_releases/

## Writing correct CMSSW release version to cmssw_info file
cd \$DQMGUI_MODE_PATH

# Script generated by cmssw_deploy script
file_name="cmswrapper.sh"
CMSSW_VERSION=\$(grep -oh "\w*CMSSW_\w*" ./\$file_name)

cd $INSTALLATION_DIR/scripts

sed -i "2s/.*/\$CMSSW_VERSION/" cmssw_info

mkdir -p $DQMGUI_DATA_DIR
# This does not look like a good idea...
sudo chmod -R 777 $DQMGUI_DATA_DIR
sudo chmod -R 777 $INSTALLATION_DIR
export PYTHONPATH=$INSTALLATION_DIR/python/.python_packages

%files
%defattr(755, root, root, 777)
$INSTALLATION_DIR

EOF

# Create directories for building the RPM in the current machine
mkdir -p RPMBUILD/{RPMS/{noarch},SPECS,BUILD,SOURCES,SRPMS}
rpmbuild --define "_topdir $(pwd)/RPMBUILD" -bb dqmgui-lib.spec
mv ./RPMBUILD/RPMS/x86_64/DQM_GUI-${DQM_GUI_RELEASE_VERSION}-1.x86_64.rpm ./
rm -rf dqmgui dqmgui_rpm RPMBUILD

echo "Build was successful!"
